spring:
  application:
    name: greeting-service

greeting-service:
  greeting: "Pronto"
  default-value: "Manito"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
